### PR TITLE
HACK: Fix missing malloc lock caused by WEAK property

### PR DESCRIPTION
**Pull request by hansbinderup**
This is a hack to ensure that the linker won't link against the stub.

### CODE REVIEW

**Review by mads-bn — APPROVED** [review]
I would probably have left an inline comment about the almost invisible) HACK.
Hopefully you will pick it up again after vacation, but please be sure we dont forget :-)

**Comment by mads-bn** [comment]
No JIRA ref (or too many crash JIRAs)?
You could also include the work "Hotfix", e.g.:
 "MOZ-0 Hotfix/HACK: FEP crashed due to missing malloc lock caused by WEAK property".

**Comment by hansbinderup** [comment]
> No JIRA ref (or too many crash JIRAs)? You could also include the work "Hotfix", e.g.: "MOZ-0 Hotfix/HACK: FEP crashed due to missing malloc lock caused by WEAK property".

I usually don't attach Jiras on public repos :wink:

**Comment by hansbinderup** [comment]
> I would probably have left an inline comment about the almost invisible) HACK. Hopefully you will pick it up again after vacation, but please be sure we dont forget :-)

hoping to revert this - I'll look more into it after holidays. Thought that the git history "HACK" would speak for itself :smile:

**Pull request merged**
